### ISSUE TITLE
Speed animation config

### ISSUE THREAD

**Issue by ScreamZ** [dkress59/react-loading-icons#4]
Hello, thanks for this library,

is there any way to tweak the speed of the animation rotation ?

Thanks

**Comment by dkress59** [comment]
Hey @ScreamZ , thanks for using it!

Of course, there is – I'll push an update later today, to make it easier to use :)

Thanks for reaching out! I'll get back to you.

**Comment by dkress59** [comment]
Done! After updating the package you can use the `speed` prop (`1` = 100%) to control the speed of the animation. Enjoy and let me know if it's what you were looking for!

**Comment by ScreamZ** [comment]
@dkress59 Thank you ❤️
