### ISSUE TITLE
Support for tree shaking

### ISSUE THREAD

**Issue by dimitarnestorov** [dkress59/react-loading-icons#9]
In my project I use only one icon but when I build the app and run a bundle analyzer all icons are bundled:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/8790386/168831554-696611e4-07f5-4f06-8dcc-23bcba271a5a.png">

Most packages usually ship a second build which uses ES6 imports (this is required by many bundlers for tree shaking). To point bundlers at that build they have a `module` entry in  `package.json` which points to the index file of the ESM build. Here's an example of Redux Toolkit:

https://github.com/reduxjs/redux-toolkit/blob/c6164cbd45d0f9665e775295f7986b666035e0ab/packages/toolkit/package.json#L26

<table>
  <tr>
    <td><img alt="package.json" src="https://user-images.githubusercontent.com/8790386/168833086-9829e855-aa10-4af8-9548-d932b41760ca.png"></td>
    <td><img alt="dist/redux-toolkit.esm.js" src="https://user-images.githubusercontent.com/8790386/168832660-aff24622-0fe7-4663-9d4d-2f5c5af87f4a.png"></td>
  </tr>
</table>

A workaround I use for now:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/8790386/168829768-2aeb4a18-c053-4975-9227-c7bfc4ea9682.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/8790386/168831083-c53b123d-6c9d-43ca-97a5-49d94b05c66d.png">

It would be awesome if I didn't have to use the workaround. Let me know if you need help.

**Comment by dkress59** [comment]
Heya @dimitarnestorov, thanks for reaching out!

I thought the way you did it, the work-around, would be enough – but you're right, that's what the "module" field in the package.json is for, after all, isn't it?!
Once I have fixed the [CI](https://github.com/dkress59/react-loading-icons/actions), I'll release v1.1.0 – which should support ESM tree shaking out-of-the-box.

Many thanks for your input, let me know if v1.1.0 works for you!

**Comment by dkress59** [comment]
v1.1.0 was released yesterday, have you checked if it works for you, @dimitarnestorov?

**Comment by DimitarNestorov** [comment]
Yes, seems to be working. Thanks for the quick fix!

|Before (v1.0.8)|After (v1.1.0)|
|-|-|
|<img width="635" alt="image" src="https://user-images.githubusercontent.com/8790386/169031175-302a576c-c496-44c4-8a47-77e7c92c6887.png">|<img width="623" alt="image" src="https://user-images.githubusercontent.com/8790386/169031269-0125f525-44de-4bf9-8033-391db6662e2f.png">|
